### ISSUE TITLE
Make "C" access stats

### ISSUE THREAD

**Issue by CoffeeHaus** [TeamLaw/TowerCrawl#22]
The player needs to be able to see his/her stats. This includes damage and health/max health. 
Right now we will have it display and hit any key to go back to main screen.

**Comment by CoffeeHaus** [comment]
Also include how much experience the player has and how much they need to level up. 
Display current level as well.

**Comment by CoffeeHaus** [comment]
needs to be 'c' is because s is already used

**Comment by papa0four** [comment]
added some printf statements that should print the players current damage, health, overall health and current level if person enters the c key when not in an encounter
